name: RecordSystemAudio

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest
    env:
      Solution_Name: RecordSystemAudio/RecordSystemAudio.sln
      Wap_Project_Directory: RecordSystemAudio/RecordSystemAudio/
      Wap_Project_Path: RecordSystemAudio/RecordSystemAudio/RecordSystemAudio.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: dotnet restore $env:Solution_Name

      #Build de app
      - name: Restore the application
        run: dotnet build $env:Solution_Name
