# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: RecordSystemAudio-Deploy 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./RecordSystemAudio.sln

    - name: Build
      run: dotnet build ./RecordSystemAudio.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./RecordSystemAudio.sln --configuration Release --no-build
